### ISSUE TITLE
libcfitsio.a linking errors

### ISSUE THREAD

**Issue by demitri** [esheldon/fitsio#134]
Using the current master (commit [fb09a1d](https://github.com/esheldon/fitsio/commit/fb09a1db26baee609c29594ef37bdaa0c420fdef), 20 Sep 2017), I'm getting the following errors during `python setup.py build`:

```
gcc -bundle -undefined dynamic_lookup -L/usr/local/anaconda/lib -L/usr/local/anaconda/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/fitsio/fitsio_pywrap.o build/temp.macosx-10.7-x86_64-3.6/cfitsio3370patch/libcfitsio.a -L/usr/local/anaconda/lib -lbz2 -o build/lib.macosx-10.7-x86_64-3.6/fitsio/_fitsio_wrap.cpython-36m-darwin.so
ld: warning: object file (build/temp.macosx-10.7-x86_64-3.6/cfitsio3370patch/libcfitsio.a(cfileio.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (build/temp.macosx-10.7-x86_64-3.6/cfitsio3370patch/libcfitsio.a(putkey.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (build/temp.macosx-10.7-x86_64-3.6/cfitsio3370patch/libcfitsio.a(fitscore.o)) was built for newer OSX version (10.12) than being linked (10.7)
```

The list continues for every `*.o` file.

**Comment by demitri** [comment]
Obviously this is a Mac-specific issue. The fix is to set this environment variable:

`export MACOSX_DEPLOYMENT_TARGET="10.7"`

I’ll leave it to someone else to set this in the right place. For non-Mac developers, the “deployment target” is the minimum macOS version that the code compiled is targeted to work on.

**Comment by esheldon** [comment]
Is this still a problem?  Are there any other mac folks out there willing to help?

**Comment by beckermr** [comment]
This issue is not something fitsio can fix on its own. We cannot enforce which versions or even which minimum OSX version the library is compiled for. Adjusting the users environment in the setup.py is not a good idea at all. Also, the conda package handles this correctly FWIW. 

Given that this is a compiler warning, not an error, everything appears to be working, and the version stuff I mentioned above, we will have to permanently punt on this one. 

I am going to close this issue, but feel free to reopen if you want to discuss more!
