### ISSUE TITLE
file corruption with append()

### ISSUE THREAD

**Issue by pmelchior** [esheldon/fitsio#28]
I traced an odd bug to the following piece of code:

``` python
fits = fitsio.FITS(fitsfile, 'rw')
for counter in range(N):
    # initialized
    data = np.empty(n_gal, dtype=(...))
    # filled with some results
    data = fromSomeFancyCalculation()
    if counter == 0:
            fits.write(data)
    else:
            fits[-1].append(data)
```

The data portion of some of the entries has the right format, but the content is jumbled. I tried to reproduce it by working with the same input data, but the problem is intermittent. I could not confirm completely, but it seems that it's always entire blocks of data being corrupted, and the next call to `fits[-1].append(data)` works again as intended.

My suspicion is that `append()` tries to write `data` from a previous iteration that is already overwritten by `data = np.empty()`. However, there's no handle to wait for the completion of `append()`, right?

**Comment by kadrlica** [comment]
I have encountered similar file corruption when running a loop over `insert_column()`. Again the issue is intermittent and I've only seen it when running multiple parallel jobs. The jobs are parallelized by file (no two jobs are writing to the same file), so I wouldn't expect them to conflict directly. I've always assumed that this is a condition resulting from overloading the file system (i.e., too much file I/O at one time).

**Comment by esheldon** [comment]
by parallel jobs, do you mean "using a single python instance using multiprocessing" or "different python jobs"?

**Comment by kadrlica** [comment]
I mean multiple python instances.
