### ISSUE TITLE
GZIP_2 does not appear to do lossless compression

### ISSUE THREAD

**Issue by erykoff** [esheldon/fitsio#385]
Running the following snippet with fitsio=1.2.0 from conda-forge fails:

```
import numpy as np
import fitsio


np.random.seed(12345)

arr = np.random.uniform(size=1_000_000, low=-100.0, high=100.0)

with fitsio.FITS("test_fits.fits", mode="rw", clobber=True) as f:
    f.write(arr, compress="GZIP_2", tile_dims=(100_000, ), qlevel=0.0, qmethod="NO_DITHER")

arr_in = fitsio.read("test_fits.fits")

np.testing.assert_array_equal(arr_in, arr)
```

I've tried combinations of `None` and `0.0` and nothing seems to get it to lossless compression.

**Comment by beckermr** [comment]
Yikes this one is bad.

**Comment by esheldon** [comment]
None converts to 0.0 internally

**Comment by esheldon** [comment]
histogram of differences
![diff](https://github.com/esheldon/fitsio/assets/621661/cfba1224-3551-4684-a117-8e0eadbe2064)

**Comment by esheldon** [comment]
You can get lossless gzip compression by putting a .gz on the filename
```
fitsio.write('test.fits.gz', image)
```
This is how I've always done it.

Looking at our tests, they are indeed expecting that even gzip is lossy when it is done as above, setting fits compression when creating the HDU.

The docs do not indicate the ability to do lossless gzip in that way, although it must be possible since astropy supports it.  Will keep digging
